version: "3"
services:
  content:
    image: content-generator:0.1
    environment:
      - RABBIT=http://rabbit:15672/api/exchanges/%2F/contentexchange/publish
      - RABBIT_LOGIN=rabbit
      - RABBIT_PASS=rabbit
      - URL=https://httpbin.org/html
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
  rabbit:
    image: rabbitmq:3.13.1-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NODENAME=rabbit
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
  flinkjobmanager:
    image: flink:1.16.3
    command: ["standalone-job", "--job-classname", "me.patrzyk.ChangeDetector"]
    ports:
      - "8081:8081"
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address: flinkjobmanager"
    volumes:
      - ./target/change-detector-1.0-SNAPSHOT.jar:/opt/flink/usrlib/change-detector-1.0-SNAPSHOT.jar
    depends_on:
      rabbit:
        condition: service_healthy
  flinktask:
    image: flink:1.16.3
    command: taskmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address: flinkjobmanager"
    volumes:
      - ./target/change-detector-1.0-SNAPSHOT.jar:/opt/flink/usrlib/change-detector-1.0-SNAPSHOT.jar
    depends_on:
      rabbit:
        condition: service_healthy
