version: "3"
services:
    # links:
    #   - rabbit
    # depends_on:
    #   rabbit:
    #     condition: service_healthy
  rabbit:
    image: rabbitmq:3.13.1-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NODENAME=rabbit
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
